
const types = {
  RULE_LIST_REQUESTED: 'RULE_LIST_REQUESTED',
  RULE_LIST_RECEIVED: 'RULE_LIST_RECEIVED',
  RULE_LIST_FAILED: 'RULE_LIST_FAILED',
  RULE_DELETE_REQUESTED: 'RULE_DELETE_REQUESTED',
  RULE_DELETE_SUCCEEDED: 'RULE_DELETE_SUCCEEDED',
  RULE_DELETE_FAILED: 'RULE_DELETE_FAILED',
  RULE_DELETE_STATUS_CLEARED: 'RULE_DELETE_STATUS_CLEARED'
};

export default types;